In [1]:

import numpy as np

In [6]:
standard_basis= np.array([[1,0], [0,1]])


print("standard_basis", standard_basis)
print("standard_basis", standard_basis.shape)
print("standard_basis", standard_basis.ndim)

print("np", np.linalg.matrix_rank(standard_basis))
print("len", len(standard_basis))

another_basis = np.array([[1,1], [-1, 2]])

print("another_basis", another_basis)
print("another_basis", another_basis.shape)
print("another_basis", another_basis.ndim)

print("np", np.linalg.matrix_rank(another_basis))
print("len", len(another_basis))





standard_basis [[1 0]
 [0 1]]
standard_basis (2, 2)
standard_basis 2
np 2
len 2
another_basis [[ 1  1]
 [-1  2]]
another_basis (2, 2)
another_basis 2
np 2
len 2


In [9]:
# Test len
A = np.array([[1,2], [3,4], [5,6]])
print("A", A)
print("A", A.shape)
print("A", A.ndim)
print("len", len(A))


spanning_set = np.array([[1,0],[1,1], [0,1] ])

print("spanning_set", spanning_set)
print("spanning_set", spanning_set.shape)
print("spanning_set", spanning_set.ndim)
print("len", len(spanning_set))
print("np", np.linalg.matrix_rank(spanning_set))



A [[1 2]
 [3 4]
 [5 6]]
A (3, 2)
A 2
len 3
spanning_set [[1 0]
 [1 1]
 [0 1]]
spanning_set (3, 2)
spanning_set 2
len 3
np 2


In [13]:
# standard basis
print(np.eye(3))

v = np.array([3,4])
e1 = np.array([1,0])
e2 = np.array([0,1])

print(v)
print(e1)
print(e2)

print(f"v = {v[0]} * e1 + {v[1]} * e2")


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[3 4]
[1 0]
[0 1]
v = 3 * e1 + 4 * e2
