In [2]:
import numpy as np

In [6]:

A = np.array([[1,2,3,
               4,5,6,
               7,8,9]])
print("A", A)

print("A", A.shape)
print("A", A.ndim)
print("A", A.shape[0], A.shape[1])

A [[1 2 3 4 5 6 7 8 9]]
A (1, 9)
A 2
A 1 9


In [11]:
# 3 x 2
A = np.array([[1,2],
              [3,4],
              [5,6]])
print("A", A)
print("A", A.shape)
print("A", A.ndim)

A1=np.array([10,20,30])
print("A1", A1)
print("A1", A1.shape)
print("A1", A1.ndim)

A2=np.array([[10,20,30]])
print("A2", A2)
print("A2", A2.shape)
print("A2", A2.ndim)

A3=np.array([[10],[20],[30]])
print("A3", A3)
print("A3", A3.shape)
print("A3", A3.ndim)

# 2x2の行列が3枚重なっているイメージ
A4 = np.array([
    [[1, 2], [3, 4]], # 1枚目
    [[5, 6], [7, 8]], # 2枚目
    [[9, 0], [1, 2]]  # 3枚目
])
print("A4", A4)
print("A4", A4.shape)
print("A4", A4.ndim)




A [[1 2]
 [3 4]
 [5 6]]
A (3, 2)
A 2
A1 [10 20 30]
A1 (3,)
A1 1
A2 [[10 20 30]]
A2 (1, 3)
A2 2
A3 [[10]
 [20]
 [30]]
A3 (3, 1)
A3 2
A4 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[9 0]
  [1 2]]]
A4 (3, 2, 2)
A4 3


In [18]:
A = np.arange(12)
print("A", A)
print("A", A.shape)
print("A", A.ndim)

reshaped = A.reshape(3,-1)
print("reshaped", reshaped)
print("reshaped", reshaped.shape)
print("reshaped", reshaped.ndim)

reshaped = A.reshape(-1,4)
print("reshaped", reshaped)
print("reshaped", reshaped.shape)
print("reshaped", reshaped.ndim)

A [ 0  1  2  3  4  5  6  7  8  9 10 11]
A (12,)
A 1
reshaped [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshaped (3, 4)
reshaped 2
reshaped [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshaped (3, 4)
reshaped 2


In [ ]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

C = A @ B
print("C", C)
print("C", C.shape)
print("C", C.ndim)


C [[19 22]
 [43 50]]
C (2, 2)
C 2
