In [6]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm

In [ ]:
A = np.array([[1,2,3],[3,4,5]])
print(A, A.shape)

# TODO: reshape

[[1 2 3]
 [3 4 5]] (2, 3)


In [ ]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

print(A, B)
print(A @ B)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [ ]:
A = np.array([[1,2,3],[4,5,6]])
x = np.array([1,2,3])

y = A @ x
print(y, y.shape)


[14 32]


In [13]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

AB = A @ B
BA = B @ A

print(AB, BA)
print("AB != BA", np.array_equal(AB, BA))

[[19 22]
 [43 50]] [[23 34]
 [31 46]]
AB != BA False


In [19]:
# Transpose
A = np.array([[1,2],[3,4]])
print(A)
print(A.T)
print(A.T.T)
print("equal", np.array_equal(A, A.T.T))

B = np.array([[4,5],[6,7]])
print(B)
print(B.T)

# 3. (AB)^T = B^T A^T の確認

AB = A @ B
AB_T = AB.T

B_T_A_T = B.T @ A.T
print("(AB)^T, B^T A^T", np.array_equal(AB_T, B_T_A_T))




[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 2]
 [3 4]]
equal True
[[4 5]
 [6 7]]
[[4 6]
 [5 7]]
(AB)^T, B^T A^T True


In [22]:
# Identity Matrix
A = np.array([[1, 2],
              [3, 4]])

print("A", A)
det_A = np.linalg.det(A)
print("det_A", det_A)

A_inv = np.linalg.inv(A)
print("A_inv", A_inv)

if abs(det_A) > 1e-10:
    A_inv = np.linalg.inv(A)
    print("A_inv", A_inv)

    I = A @ A_inv
    E = np.eye(2)
    print("I", I)
    print("E", E)
    print("I == I", np.array_equal(I, E))
else:
    print("det_A is too small, A is not invertible")


A [[1 2]
 [3 4]]
det_A -2.0000000000000004
A_inv [[-2.   1. ]
 [ 1.5 -0.5]]
A_inv [[-2.   1. ]
 [ 1.5 -0.5]]
I [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
E [[1. 0.]
 [0. 1.]]
I == I False


In [29]:
A = np.array([[1, 2],
              [2, 4]])

print("A", A)

det_A = np.linalg.det(A)
print("det_A", det_A)

if abs(det_A) < 1e-10:
    print("det_A is too small, A is not invertible")
    rank_A = np.linalg.matrix_rank(A)
    print("rank_A", rank_A)
    print("A", A.shape)

    try:
        A_inv = np.linalg.inv(A)
    except np.linalg.LinAlgError as e:
        print("error", e)


A [[1 2]
 [2 4]]
det_A 0.0
det_A is too small, A is not invertible
rank_A 1
A (2, 2)
error Singular matrix


In [ ]:
# Inverse Matrix
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("A", A)
print("B", B)

A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)

print("A_inv", A_inv)
print("B_inv", B_inv)

# A_inv_B = A_inv @ B
# print("A_inv @ B", A_inv_B)

A_inv_inv = np.linalg.inv(A_inv)
print("A_inv_inv == A", np.allclose(A_inv_inv, A))

# (AB)^(-1) = B^(-1) A^(-1) の確認
AB = A @ B
print("AB", AB)
AB_inv = np.linalg.inv(AB)
B_inv_A_inv = B_inv @ A_inv

print("equal", np.allclose(AB_inv, B_inv_A_inv))


A [[1 2]
 [3 4]]
B [[5 6]
 [7 8]]
A_inv [[-2.   1. ]
 [ 1.5 -0.5]]
B_inv [[-4.   3. ]
 [ 3.5 -2.5]]
A_inv_inv == A True
AB [[19 22]
 [43 50]]
equal True


In [39]:
# Identity Matrix
I1 = np.eye(2)
I = np.eye(3)

print("I1", I1)
print("I", I)

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


A_I = A @ I
I_A = I @ A

print("A", A)
print("A @ I", A @ I)
print("I @ A", I @ A)
print("A_I == I_A", np.array_equal(A_I, I_A))


I1 [[1. 0.]
 [0. 1.]]
I [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A [[1 2 3]
 [4 5 6]
 [7 8 9]]
A @ I [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
I @ A [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
A_I == I_A True


In [41]:
# Symmetric Matrix
A = np.array([[1, 2, 3],
              [2, 4, 5],
              [3, 5, 6]])
print("A", A)
print("A.T", A.T)

print("A == A.T", np.array_equal(A, A.T))


A [[1 2 3]
 [2 4 5]
 [3 5 6]]
A.T [[1 2 3]
 [2 4 5]
 [3 5 6]]
A == A.T True


In [49]:
# Orthogonal Matrix

# **直交行列（Orthogonal Matrix）**は、転置が逆行列と等しい行列です。

# $$A^T = A^{-1} \quad \text{つまり} \quad A^T A = AA^T = I$$

pi = np.pi # 180
theta = np.pi / 4 # 45

print("np.pi", pi)
print("theta", theta)
print("np.cos(pi / 3)", np.cos(pi / 3))
print("np.sin(pi / 3)", np.sin(pi / 3))

# print("np.cos(theta)", np.cos(theta))
# print("np.sin(theta)", np.sin(theta))

# この行列 $R$ は、座標平面上の点を原点を中心に反時計回りに角度 $\theta$ だけ回転させる操作を表しています。
R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta), np.cos(theta)]])
print("R", R)
print("R.T", R.T)
print("np.linalg.inv(R)", np.linalg.inv(R))



np.pi 3.141592653589793
theta 0.7853981633974483
np.cos(pi / 3) 0.5000000000000001
np.sin(pi / 3) 0.8660254037844386
R [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
R.T [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
np.linalg.inv(R) [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
