# 線形代数：行列とベクトルの演算 (2.2 Matrices)

このノートブックでは、**行列とベクトルの演算**について基礎から学びます。

> **重要性**: 機械学習では、大量のデータを「行列」という形にまとめて一度に計算します。

## 目次
1. [行列の基本](#行列の基本)
2. [行列の掛け算](#行列の掛け算)
3. [転置行列](#転置行列)
4. [逆行列](#逆行列)
5. [行列の性質と定理](#行列の性質と定理)
6. [実装例と演習](#実装例と演習)
7. [機械学習での応用](#機械学習での応用)

> **チェックポイント**: 行列の掛け算、逆行列、転置行列の定義と性質は必須です。これらは第5章の「ベクトル微積分」や第9章の「線形回帰」で頻繁に使われます。


---

## 必要なライブラリのインポート


In [19]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm

# 日本語フォントの設定
try:
    jp_fonts = ['Hiragino Sans', 'Hiragino Kaku Gothic ProN', 'Yu Gothic',
                'Noto Sans CJK JP', 'AppleGothic', 'Arial Unicode MS']
    available_fonts = [f.name for f in fm.fontManager.ttflist]

    font_found = False
    for font_name in jp_fonts:
        if font_name in available_fonts:
            plt.rcParams['font.family'] = font_name
            font_found = True
            print(f"Using font: {font_name}")
            break

    if not font_found:
        plt.rcParams['font.family'] = 'sans-serif'
        plt.rcParams['font.sans-serif'] = ['Hiragino Sans', 'Hiragino Kaku Gothic ProN',
                                            'Yu Gothic', 'Meiryo', 'MS Gothic', 'DejaVu Sans']
        print("Using fallback font configuration")
except Exception as e:
    print(f"Font configuration warning: {e}")
    plt.rcParams['font.family'] = 'sans-serif'

plt.rcParams['mathtext.default'] = 'regular'
plt.rcParams['axes.unicode_minus'] = False
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

print("ライブラリのインポートが完了しました。")


Using font: Hiragino Sans
ライブラリのインポートが完了しました。


---

## 1. 行列の基本

### 1.1 行列の定義

**行列（Matrix）**は、数値を長方形に並べたものです。

$m \times n$ 行列 $A$ は以下のように表されます：

$$A = \begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{pmatrix}$$

- $m$: 行数（rows）
- $n$: 列数（columns）
- $a_{ij}$: $i$行目、$j$列目の要素


In [37]:
# 行列の作成例
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("行列 A (3×3):")
print(A)
print(f"\n形状: {A.shape}")
print(f"行数: {A.shape[0]}, 列数: {A.shape[1]}")

# ベクトルの作成例
v = np.array([1, 2, 3])
print(f"\nベクトル v: {v}")
print(f"形状: {v.shape}")

# 列ベクトルとして扱う
v_col = v.reshape(-1, 1)
print(f"\n列ベクトル v (3×1):")
print(v_col)


行列 A (3×3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

形状: (3, 3)
行数: 3, 列数: 3

ベクトル v: [1 2 3]
形状: (3,)

列ベクトル v (3×1):
[[1]
 [2]
 [3]]


---

## 2. 行列の掛け算

### 2.1 行列同士の掛け算

**行列の掛け算**は、機械学習の核心となる演算です。

$A$ が $m \times n$ 行列、$B$ が $n \times p$ 行列のとき、積 $C = AB$ は $m \times p$ 行列になります。

**重要な条件**: $A$ の列数 = $B$ の行数 でなければなりません。

$$C_{ij} = \sum_{k=1}^{n} A_{ik} B_{kj}$$

### 2.2 行列とベクトルの掛け算

行列 $A$ ($m \times n$) とベクトル $x$ ($n \times 1$) の積：

$$y = Ax$$

結果は $m \times 1$ ベクトルになります。


In [21]:
# 行列同士の掛け算
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("行列 A:")
print(A)
print("\n行列 B:")
print(B)

# 行列の掛け算（@演算子またはnp.dot）
C = A @ B
print("\n積 C = A @ B:")
print(C)

# 手動計算の確認
print("\n手動計算の確認:")
print(f"C[0,0] = A[0,0]*B[0,0] + A[0,1]*B[1,0] = {A[0,0]}*{B[0,0]} + {A[0,1]}*{B[1,0]} = {A[0,0]*B[0,0] + A[0,1]*B[1,0]}")
print(f"C[0,1] = A[0,0]*B[0,1] + A[0,1]*B[1,1] = {A[0,0]}*{B[0,1]} + {A[0,1]}*{B[1,1]} = {A[0,0]*B[0,1] + A[0,1]*B[1,1]}")


行列 A:
[[1 2]
 [3 4]]

行列 B:
[[5 6]
 [7 8]]

積 C = A @ B:
[[19 22]
 [43 50]]

手動計算の確認:
C[0,0] = A[0,0]*B[0,0] + A[0,1]*B[1,0] = 1*5 + 2*7 = 19
C[0,1] = A[0,0]*B[0,1] + A[0,1]*B[1,1] = 1*6 + 2*8 = 22


In [22]:
# 行列とベクトルの掛け算
A = np.array([[1, 2, 3],
              [4, 5, 6]])

x = np.array([1, 2, 3])

print("行列 A (2×3):")
print(A)
print(f"\nベクトル x: {x}")

# 行列とベクトルの積
y = A @ x
print(f"\n積 y = A @ x: {y}")
print(f"形状: {y.shape}")

# 手動計算の確認
print("\n手動計算:")
print(f"y[0] = A[0,0]*x[0] + A[0,1]*x[1] + A[0,2]*x[2] = {A[0,0]}*{x[0]} + {A[0,1]}*{x[1]} + {A[0,2]}*{x[2]} = {A[0,0]*x[0] + A[0,1]*x[1] + A[0,2]*x[2]}")
print(f"y[1] = A[1,0]*x[0] + A[1,1]*x[1] + A[1,2]*x[2] = {A[1,0]}*{x[0]} + {A[1,1]}*{x[1]} + {A[1,2]}*{x[2]} = {A[1,0]*x[0] + A[1,1]*x[1] + A[1,2]*x[2]}")


行列 A (2×3):
[[1 2 3]
 [4 5 6]]

ベクトル x: [1 2 3]

積 y = A @ x: [14 32]
形状: (2,)

手動計算:
y[0] = A[0,0]*x[0] + A[0,1]*x[1] + A[0,2]*x[2] = 1*1 + 2*2 + 3*3 = 14
y[1] = A[1,0]*x[0] + A[1,1]*x[1] + A[1,2]*x[2] = 4*1 + 5*2 + 6*3 = 32


### 2.3 行列の掛け算の性質

1. **結合則**: $(AB)C = A(BC)$
2. **分配則**: $A(B + C) = AB + AC$
3. **非可換性**: 一般に $AB \neq BA$（順序が重要！）

**注意**: 行列の掛け算は可換ではありません！


In [23]:
# 非可換性の確認
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

AB = A @ B
BA = B @ A

print("A @ B:")
print(AB)
print("\nB @ A:")
print(BA)
print("\nA @ B ≠ B @ A であることを確認:")
print(f"等しいか？ {np.array_equal(AB, BA)}")


A @ B:
[[19 22]
 [43 50]]

B @ A:
[[23 34]
 [31 46]]

A @ B ≠ B @ A であることを確認:
等しいか？ False


---

## 3. 転置行列

### 3.1 転置行列の定義

**転置行列（Transpose）**は、行列の行と列を入れ替えたものです。

$A$ が $m \times n$ 行列のとき、転置行列 $A^T$ は $n \times m$ 行列になります。

$$(A^T)_{ij} = A_{ji}$$

### 3.2 転置行列の性質

1. $(A^T)^T = A$
2. $(A + B)^T = A^T + B^T$
3. $(AB)^T = B^T A^T$ （重要！順序が逆になる）
4. $(cA)^T = cA^T$（$c$ はスカラー）


In [24]:
# 転置行列の例
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print("元の行列 A (2×3):")
print(A)
print(f"形状: {A.shape}")

A_T = A.T
print("\n転置行列 A^T (3×2):")
print(A_T)
print(f"形状: {A_T.shape}")

# 転置の転置は元に戻る
print("\n(A^T)^T = A の確認:")
print(np.array_equal((A_T).T, A))


元の行列 A (2×3):
[[1 2 3]
 [4 5 6]]
形状: (2, 3)

転置行列 A^T (3×2):
[[1 4]
 [2 5]
 [3 6]]
形状: (3, 2)

(A^T)^T = A の確認:
True


In [25]:
# (AB)^T = B^T A^T の確認
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

AB = A @ B
AB_T = AB.T

B_T_A_T = B.T @ A.T

print("(AB)^T:")
print(AB_T)
print("\nB^T A^T:")
print(B_T_A_T)
print("\n等しいか？", np.allclose(AB_T, B_T_A_T))


(AB)^T:
[[19 43]
 [22 50]]

B^T A^T:
[[19 43]
 [22 50]]

等しいか？ True


---

## 4. 逆行列

### 4.1 逆行列の定義

**逆行列（Inverse Matrix）**は、正方行列に対して定義されます。

$n \times n$ 正方行列 $A$ に対して、$AA^{-1} = A^{-1}A = I$ を満たす行列 $A^{-1}$ が存在するとき、$A$ は**正則（invertible）**または**可逆（nonsingular）**であるといいます。

ここで、$I$ は単位行列（Identity Matrix）です。

### 4.2 逆行列が存在する条件

- 行列式（determinant）が 0 でない: $\det(A) \neq 0$
- 行列のランクが最大: $\text{rank}(A) = n$
- 列ベクトル（または行ベクトル）が線形独立


In [ ]:
# 逆行列の計算
A = np.array([[1, 2],
              [3, 4]])

print("行列 A:")
print(A)

# 行列式の計算
det_A = np.linalg.det(A)
print(f"\n行列式 det(A) = {det_A:.4f}")

# ンピュータの計算では、理論上 $0$ になるはずの値が 0.0000000000000001 のように非常に小さな値になることがあります。
if abs(det_A) > 1e-10:  # 数値誤差を考慮
    A_inv = np.linalg.inv(A)
    print("\n逆行列 A^(-1):")
    print(A_inv)

    # 検証: A @ A^(-1) = I
    I = A @ A_inv
    print("\n検証: A @ A^(-1) (単位行列に近い):")
    print(I)
    print("\n単位行列に近いか？", np.allclose(I, np.eye(2)))
else:
    print("\n行列式が0に近いため、逆行列は存在しません。")


行列 A:
[[1 2]
 [3 4]]

行列式 det(A) = -2.0000

逆行列 A^(-1):
[[-2.   1. ]
 [ 1.5 -0.5]]

検証: A @ A^(-1) (単位行列に近い):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

単位行列に近いか？ True


In [27]:
# 逆行列が存在しない例
A = np.array([[1, 2],
              [2, 4]])

print("行列 A:")
print(A)

det_A = np.linalg.det(A)
print(f"\n行列式 det(A) = {det_A:.4f}")

if abs(det_A) < 1e-10:
    print("\n行列式が0のため、逆行列は存在しません。")
    print("この行列は特異（singular）です。")

    # ランクの確認
    rank_A = np.linalg.matrix_rank(A)
    print(f"ランク: {rank_A} (最大ランク: {A.shape[0]})")

    # 逆行列を計算しようとするとエラーになる
    try:
        A_inv = np.linalg.inv(A)
    except np.linalg.LinAlgError as e:
        print(f"\nエラー: {e}")


行列 A:
[[1 2]
 [2 4]]

行列式 det(A) = 0.0000

行列式が0のため、逆行列は存在しません。
この行列は特異（singular）です。
ランク: 1 (最大ランク: 2)

エラー: Singular matrix


### 4.3 逆行列の性質

1. $(A^{-1})^{-1} = A$
2. $(AB)^{-1} = B^{-1}A^{-1}$ （重要！順序が逆になる）
3. $(A^T)^{-1} = (A^{-1})^T$
4. $\det(A^{-1}) = \frac{1}{\det(A)}$


In [28]:
# 逆行列の性質の確認
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)

# (AB)^(-1) = B^(-1) A^(-1) の確認
AB = A @ B
AB_inv = np.linalg.inv(AB)
B_inv_A_inv = B_inv @ A_inv

print("(AB)^(-1):")
print(AB_inv)
print("\nB^(-1) A^(-1):")
print(B_inv_A_inv)
print("\n等しいか？", np.allclose(AB_inv, B_inv_A_inv))

# (A^(-1))^(-1) = A の確認
print("\n(A^(-1))^(-1) = A の確認:")
print(np.allclose(np.linalg.inv(A_inv), A))


(AB)^(-1):
[[ 12.5   -5.5 ]
 [-10.75   4.75]]

B^(-1) A^(-1):
[[ 12.5   -5.5 ]
 [-10.75   4.75]]

等しいか？ True

(A^(-1))^(-1) = A の確認:
True


---

## 5. 行列の性質と定理

### 5.1 単位行列

**単位行列（Identity Matrix）** $I$ は対角成分がすべて1、それ以外が0の正方行列です。

$$I = \begin{pmatrix}
1 & 0 & \cdots & 0 \\
0 & 1 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & 1
\end{pmatrix}$$

任意の行列 $A$ に対して：$AI = IA = A$

### 5.2 対称行列

**対称行列（Symmetric Matrix）**は、転置しても変わらない行列です。

$$A^T = A$$

### 5.3 直交行列

**直交行列（Orthogonal Matrix）**は、転置が逆行列と等しい行列です。

$$A^T = A^{-1} \quad \text{つまり} \quad A^T A = AA^T = I$$


In [29]:
# 単位行列
I = np.eye(3)
print("単位行列 I (3×3):")
print(I)

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("\n行列 A:")
print(A)
print("\nA @ I = A の確認:")
print(np.array_equal(A @ I, A))
print("\nI @ A = A の確認:")
print(np.array_equal(I @ A, A))


単位行列 I (3×3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

行列 A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

A @ I = A の確認:
True

I @ A = A の確認:
True


In [30]:
# 対称行列の例
A = np.array([[1, 2, 3],
              [2, 4, 5],
              [3, 5, 6]])

print("行列 A:")
print(A)
print("\n転置行列 A^T:")
print(A.T)
print("\n対称行列か？ (A^T = A):", np.array_equal(A, A.T))


行列 A:
[[1 2 3]
 [2 4 5]
 [3 5 6]]

転置行列 A^T:
[[1 2 3]
 [2 4 5]
 [3 5 6]]

対称行列か？ (A^T = A): True


In [31]:
# 直交行列の例（回転行列）
theta = np.pi / 4  # 45度
R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta), np.cos(theta)]])

print("回転行列 R (45度回転):")
print(R)
print("\nR^T:")
print(R.T)
print("\nR^(-1):")
print(np.linalg.inv(R))
print("\n直交行列か？ (R^T = R^(-1)):", np.allclose(R.T, np.linalg.inv(R)))
print("\nR^T @ R = I の確認:")
print(np.allclose(R.T @ R, np.eye(2)))


回転行列 R (45度回転):
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

R^T:
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

R^(-1):
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

直交行列か？ (R^T = R^(-1)): True

R^T @ R = I の確認:
True


---

## 6. 実装例と演習

### 6.1 線形方程式の解法

逆行列を使って線形方程式 $Ax = b$ を解くことができます。

$$x = A^{-1}b$$


In [32]:
# 線形方程式 Ax = b を解く
A = np.array([[2, 1],
              [1, 3]])

b = np.array([5, 10])

print("連立方程式:")
print("2x + y = 5")
print("x + 3y = 10")
print(f"\n行列 A:\n{A}")
print(f"\nベクトル b: {b}")

# 方法1: 逆行列を使う
A_inv = np.linalg.inv(A)
x = A_inv @ b
print(f"\n解 x (逆行列を使う): {x}")

# 方法2: np.linalg.solve を使う（より数値的に安定）
x2 = np.linalg.solve(A, b)
print(f"解 x (solveを使う): {x2}")

# 検証
print(f"\n検証: A @ x = {A @ x}")
print(f"目標: b = {b}")
print(f"一致するか？ {np.allclose(A @ x, b)}")


連立方程式:
2x + y = 5
x + 3y = 10

行列 A:
[[2 1]
 [1 3]]

ベクトル b: [ 5 10]

解 x (逆行列を使う): [1. 3.]
解 x (solveを使う): [1. 3.]

検証: A @ x = [ 5. 10.]
目標: b = [ 5 10]
一致するか？ True


### 6.2 行列のトレース（Trace）

**トレース（Trace）**は、正方行列の対角成分の和です。

$$\text{tr}(A) = \sum_{i=1}^{n} A_{ii}$$

### 6.3 行列式（Determinant）

**行列式（Determinant）**は、正方行列に対して定義される重要な量です。

- $\det(A) \neq 0$ ならば、$A$ は正則（逆行列が存在）
- $\det(AB) = \det(A)\det(B)$
- $\det(A^T) = \det(A)$


In [33]:
# トレースと行列式
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("行列 A:")
print(A)

trace_A = np.trace(A)
det_A = np.linalg.det(A)

print(f"\nトレース tr(A) = {trace_A}")
print(f"行列式 det(A) = {det_A:.4f}")

# 手動でトレースを計算
trace_manual = sum([A[i, i] for i in range(A.shape[0])])
print(f"手動計算: {trace_manual}")


行列 A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

トレース tr(A) = 15
行列式 det(A) = -0.0000
手動計算: 15


### 6.4 演習問題

以下の問題を解いてみましょう。


In [34]:
# 演習1: 行列の掛け算
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# 問題: C = AB を計算
C = A @ B
print("演習1: C = A @ B")
print(C)

# 演習2: 転置行列
print("\n演習2: (AB)^T と B^T A^T が等しいことを確認")
AB_T = (A @ B).T
B_T_A_T = B.T @ A.T
print(f"等しいか？ {np.allclose(AB_T, B_T_A_T)}")

# 演習3: 逆行列
print("\n演習3: 逆行列の計算")
A_inv = np.linalg.inv(A)
print("A^(-1):")
print(A_inv)
print("\n検証: A @ A^(-1) = I")
print(np.allclose(A @ A_inv, np.eye(2)))


演習1: C = A @ B
[[19 22]
 [43 50]]

演習2: (AB)^T と B^T A^T が等しいことを確認
等しいか？ True

演習3: 逆行列の計算
A^(-1):
[[-2.   1. ]
 [ 1.5 -0.5]]

検証: A @ A^(-1) = I
True


---

## 7. 機械学習での応用

### 7.1 線形回帰での応用

線形回帰では、以下の正規方程式を解きます：

$$\theta = (X^T X)^{-1} X^T y$$

ここで：
- $X$: 特徴量行列（データ行列）
- $y$: 目的変数ベクトル
- $\theta$: パラメータベクトル

### 7.2 データの変換

機械学習では、データを行列として扱い、一度に多くの計算を行います。

$$Y = XW + b$$

ここで：
- $X$: 入力データ行列
- $W$: 重み行列
- $b$: バイアスベクトル
- $Y$: 出力行列


In [35]:
# 線形回帰の例（簡易版）
# データの生成
np.random.seed(42)
n_samples = 100
n_features = 3

# 特徴量行列 X (n_samples × n_features)
X = np.random.randn(n_samples, n_features)

# 真のパラメータ
true_theta = np.array([2.0, -1.5, 0.8])

# 目的変数 y = X @ theta + noise
noise = np.random.randn(n_samples) * 0.1
y = X @ true_theta + noise

print("線形回帰の例")
print(f"データ形状: X = {X.shape}, y = {y.shape}")
print(f"真のパラメータ: {true_theta}")

# 正規方程式でパラメータを推定
# theta = (X^T X)^(-1) X^T y
X_T_X = X.T @ X
X_T_X_inv = np.linalg.inv(X_T_X)
theta_hat = X_T_X_inv @ X.T @ y

print(f"\n推定されたパラメータ: {theta_hat}")
print(f"真のパラメータとの差: {np.abs(theta_hat - true_theta)}")


線形回帰の例
データ形状: X = (100, 3), y = (100,)
真のパラメータ: [ 2.  -1.5  0.8]

推定されたパラメータ: [ 1.99368101 -1.50693276  0.78981561]
真のパラメータとの差: [0.00631899 0.00693276 0.01018439]


In [36]:
# ニューラルネットワーク風の計算例
# Y = XW + b

# 入力データ (バッチサイズ × 特徴量数)
X = np.random.randn(32, 10)  # バッチサイズ32, 特徴量10

# 重み行列 (入力特徴量数 × 出力特徴量数)
W = np.random.randn(10, 5)  # 出力特徴量5

# バイアスベクトル
b = np.random.randn(5)

print("ニューラルネットワーク風の計算")
print(f"入力 X: {X.shape}")
print(f"重み W: {W.shape}")
print(f"バイアス b: {b.shape}")

# 線形変換: Y = XW + b
# ブロードキャストで b が各サンプルに加算される
Y = X @ W + b

print(f"\n出力 Y: {Y.shape}")
print(f"\n最初の3サンプルの出力:")
print(Y[:3])


ニューラルネットワーク風の計算
入力 X: (32, 10)
重み W: (10, 5)
バイアス b: (5,)

出力 Y: (32, 5)

最初の3サンプルの出力:
[[ 0.9068511   4.22186894  4.66716824 -1.54908603  1.74434124]
 [-0.48535801 -2.43521501  1.91544244  8.69424099  2.64685642]
 [ 2.57240598 -2.29880995 -1.45597904  2.17411529 -1.82873591]]


### 7.3 まとめ

このノートブックで学んだ重要な概念：

1. **行列の掛け算**: 機械学習の核心となる演算
   - 非可換性に注意: $AB \neq BA$
   - $(AB)^T = B^T A^T$

2. **転置行列**: 行と列の入れ替え
   - $(A^T)^T = A$
   - $(AB)^T = B^T A^T$

3. **逆行列**: 線形方程式を解くために重要
   - 存在条件: $\det(A) \neq 0$
   - $(AB)^{-1} = B^{-1}A^{-1}$

4. **機械学習での応用**:
   - 線形回帰: $\theta = (X^T X)^{-1} X^T y$
   - ニューラルネットワーク: $Y = XW + b$
   - 大量のデータを行列として一度に処理

これらの概念は、第5章の「ベクトル微積分」や第9章の「線形回帰」で頻繁に使われます。


---

## 参考資料

- NumPy ドキュメント: https://numpy.org/doc/stable/reference/routines.linalg.html
- 線形代数の基礎: 行列演算の理解は機械学習の基盤です
