In [7]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm

In [ ]:
# Matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("A", A)
print("A.shape", A.shape)
print("Row", A.shape[0])
print("Column", A.shape[1])

# vector
v = np.array([1,2,3])
print("v", v)
print("v.shape", v.shape) # row vector

v_col = v.reshape(-1, 1)
print("v_col", v_col)
print("v_col.shape", v_col.shape) # column vector



A [[1 2 3]
 [4 5 6]
 [7 8 9]]
A.shape (3, 3)
Row 3
Column 3
v [1 2 3]
v.shape (3,)
v_col [[1]
 [2]
 [3]]
v_col.shape (3, 1)


In [12]:
# matrix multiplication
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
C = A @ B
print("C = A @ B", C)

C = A @ B [[19 22]
 [43 50]]


In [ ]:
# vector and matrix multiplication
A = np.array([[1, 2, 3],
              [4, 5, 6]])
x = np.array([1, 2, 3])

# 2 x 3 @ 3 x 1
print("A", A)
print("x", x)

y = A @ x
print("y = A @ x", y)

A [[1 2 3]
 [4 5 6]]
x [1 2 3]
y = A @ x [14 32]
