# NumPyの基本

このノートブックでは、NumPy（Numerical Python）の基本操作について学びます。
NumPyは機械学習やデータサイエンスにおいて最も重要なライブラリの一つです。

## 目次
1. [NumPyとは](#numpyとは)
2. [配列の作成](#配列の作成)
3. [配列の属性と形状](#配列の属性と形状)
4. [配列のインデックスとスライス](#配列のインデックスとスライス)
5. [配列の演算](#配列の演算)
6. [配列の形状変更](#配列の形状変更)
7. [配列の結合と分割](#配列の結合と分割)
8. [統計関数](#統計関数)
9. [線形代数の基本操作](#線形代数の基本操作)
10. [ブロードキャスティング](#ブロードキャスティング)
11. [実践的な例](#実践的な例)


---

## 必要なライブラリのインポート


In [4]:
import numpy as np
import matplotlib.pyplot as plt

# 日本語フォントの設定（必要に応じて）
plt.rcParams['font.family'] = 'DejaVu Sans'
plt.rcParams['figure.figsize'] = (10, 6)

# NumPyのバージョン確認
print(f"NumPy version: {np.__version__}")


NumPy version: 2.0.2


---

## NumPyとは

NumPy（Numerical Python）は、Pythonで数値計算を行うための基本的なライブラリです。

### 主な特徴

- **高速な配列計算**: C言語で実装されており、Pythonのリストよりもはるかに高速
- **多次元配列**: 1次元、2次元、3次元以上の配列を効率的に扱える
- **数学関数**: 線形代数、統計、フーリエ変換などの豊富な関数
- **ブロードキャスティング**: 異なる形状の配列間での演算を自動的に処理

### なぜNumPyが重要なのか？

- 機械学習ライブラリ（scikit-learn、TensorFlow、PyTorch）の基盤
- データサイエンスで必須のツール
- ベクトル化された計算により、コードが簡潔で高速になる


---

## 配列の作成

NumPyの配列（ndarray）を作成する方法は複数あります。


In [5]:
# 1. リストから配列を作成
arr1 = np.array([1, 2, 3, 4, 5])
print("1次元配列(ベクトル):", arr1)
print("型:", type(arr1))

# 2. 2次元配列（行列）の作成
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2次元配列:")
print(arr2)

# 3. 3次元配列の作成
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3次元配列:")
print(arr3)


1次元配列(ベクトル): [1 2 3 4 5]
型: <class 'numpy.ndarray'>

2次元配列:
[[1 2 3]
 [4 5 6]]

3次元配列:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# 4. ゼロ配列の作成
zeros_1d = np.zeros(5)
zeros_2d = np.zeros((3, 4))

print("ゼロ配列（1次元）:", zeros_1d)
print("\nゼロ配列（2次元）:")
print(zeros_2d)


ゼロ配列（1次元）: [0. 0. 0. 0. 0.]

ゼロ配列（2次元）:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# 5. 1で埋めた配列の作成
ones_1d = np.ones(5)
ones_2d = np.ones((2, 3))
print("1で埋めた配列（1次元）:", ones_1d)
print("\n1で埋めた配列（2次元）:")
print(ones_2d)


1で埋めた配列（1次元）: [1. 1. 1. 1. 1.]

1で埋めた配列（2次元）:
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# 6. 範囲を指定した配列の作成
# arange: 開始値から終了値の手前まで（終了値は含まない）
arr_range = np.arange(0, 10, 2)  # 0から10未満まで2刻み
print("arange(0, 10, 2):", arr_range)

# linspace: 開始値から終了値までを等間隔に分割（終了値も含む）
arr_linspace = np.linspace(0, 10, 5)  # 0から10までを5等分
print("linspace(0, 10, 5):", arr_linspace)


arange(0, 10, 2): [0 2 4 6 8]
linspace(0, 10, 5): [ 0.   2.5  5.   7.5 10. ]


In [9]:
# 7. 単位行列の作成
identity = np.eye(3)
print("3x3の単位行列:")
print(identity)

# 8. 対角行列の作成
diagonal = np.diag([1, 2, 3, 4])
print("\n対角行列:")
print(diagonal)


3x3の単位行列:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

対角行列:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [10]:
# 9. ランダムな配列の作成
# 0から1の間の一様乱数
random_uniform = np.random.rand(3, 3)
print("一様乱数（0-1）:")
print(random_uniform)

# 正規分布に従う乱数
random_normal = np.random.randn(3, 3)
print("\n正規分布（平均0、標準偏差1）:")
print(random_normal)

# 整数の乱数
random_int = np.random.randint(0, 10, size=(3, 3))
print("\n整数乱数（0-9）:")
print(random_int)


一様乱数（0-1）:
[[0.11350649 0.81442035 0.4712612 ]
 [0.57812764 0.54128542 0.22311077]
 [0.48645399 0.00499935 0.47522666]]

正規分布（平均0、標準偏差1）:
[[-0.30144449 -0.99214677 -1.43104654]
 [ 0.2521494   0.2936399  -2.48061919]
 [ 0.16074435  0.5517132  -0.17043922]]

整数乱数（0-9）:
[[1 0 4]
 [8 9 8]
 [0 5 4]]


---

## 配列の属性と形状

NumPy配列には重要な属性があります。


In [11]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("配列:")
print(arr)
print("\n配列の属性:")
print(f"形状 (shape): {arr.shape}")  # 配列の次元
print(f"サイズ (size): {arr.size}")  # 全要素数
print(f"次元数 (ndim): {arr.ndim}")  # 次元の数
print(f"データ型 (dtype): {arr.dtype}")  # データ型
print(f"バイト数 (itemsize): {arr.itemsize} bytes")  # 1要素のバイト数
print(f"メモリサイズ (nbytes): {arr.nbytes} bytes")  # 全要素のバイト数


配列:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

配列の属性:
形状 (shape): (3, 4)
サイズ (size): 12
次元数 (ndim): 2
データ型 (dtype): int64
バイト数 (itemsize): 8 bytes
メモリサイズ (nbytes): 96 bytes


In [12]:
# データ型の指定
arr_int = np.array([1, 2, 3], dtype=np.int32)
arr_float = np.array([1, 2, 3], dtype=np.float64)
arr_complex = np.array([1, 2, 3], dtype=np.complex128)

print(f"整数型: {arr_int.dtype}")
print(f"浮動小数点型: {arr_float.dtype}")
print(f"複素数型: {arr_complex.dtype}")


整数型: int32
浮動小数点型: float64
複素数型: complex128


---

## 配列のインデックスとスライス

Pythonのリストと同様に、NumPy配列もインデックスとスライスでアクセスできます。


In [13]:
# 1次元配列のインデックスとスライス
arr = np.array([10, 20, 30, 40, 50])
print("元の配列:", arr)
print(f"arr[0] = {arr[0]}")  # 最初の要素
print(f"arr[-1] = {arr[-1]}")  # 最後の要素
print(f"arr[1:4] = {arr[1:4]}")  # インデックス1から3まで
print(f"arr[:3] = {arr[:3]}")  # 最初の3要素
print(f"arr[2:] = {arr[2:]}")  # インデックス2から最後まで


元の配列: [10 20 30 40 50]
arr[0] = 10
arr[-1] = 50
arr[1:4] = [20 30 40]
arr[:3] = [10 20 30]
arr[2:] = [30 40 50]


In [14]:
# 2次元配列のインデックスとスライス
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("元の配列:")
print(arr)
print(f"\narr[0, 0] = {arr[0, 0]}")  # 最初の行、最初の列
print(f"arr[1, 2] = {arr[1, 2]}")  # 2行目、3列目
print(f"\narr[0, :] = {arr[0, :]}")  # 最初の行全体
print(f"arr[:, 1] = {arr[:, 1]}")  # 2列目全体
print(f"\narr[0:2, 1:3] = \n{arr[0:2, 1:3]}")  # 部分配列


元の配列:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

arr[0, 0] = 1
arr[1, 2] = 7

arr[0, :] = [1 2 3 4]
arr[:, 1] = [ 2  6 10]

arr[0:2, 1:3] = 
[[2 3]
 [6 7]]


In [15]:
# ブールインデックス（条件に基づく選択）
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("元の配列:", arr)

# 5より大きい要素を選択
mask = arr > 5
print(f"\n条件 (arr > 5): {mask}")
print(f"条件を満たす要素: {arr[mask]}")

# 偶数だけを選択
even_mask = arr % 2 == 0
print(f"\n偶数: {arr[even_mask]}")


元の配列: [ 1  2  3  4  5  6  7  8  9 10]

条件 (arr > 5): [False False False False False  True  True  True  True  True]
条件を満たす要素: [ 6  7  8  9 10]

偶数: [ 2  4  6  8 10]


In [16]:
# ファンシーインデックス（配列でインデックス指定）
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
indices = [1, 3, 5, 7]
print("元の配列:", arr)
print(f"インデックス {indices} の要素: {arr[indices]}")


元の配列: [10 20 30 40 50 60 70 80]
インデックス [1, 3, 5, 7] の要素: [20 40 60 80]


---

## 配列の演算

NumPyでは、配列に対して要素ごとの演算が可能です。


In [17]:
# 基本的な算術演算
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("a =", a)
print("b =", b)
print(f"\na + b = {a + b}")  # 要素ごとの加算
print(f"a - b = {a - b}")  # 要素ごとの減算
print(f"a * b = {a * b}")  # 要素ごとの乗算（行列の積ではない）
print(f"a / b = {a / b}")  # 要素ごとの除算
print(f"a ** 2 = {a ** 2}")  # 各要素の2乗


a = [1 2 3 4]
b = [5 6 7 8]

a + b = [ 6  8 10 12]
a - b = [-4 -4 -4 -4]
a * b = [ 5 12 21 32]
a / b = [0.2        0.33333333 0.42857143 0.5       ]
a ** 2 = [ 1  4  9 16]
