# NumPy reshape() の使い方

`reshape()` は配列の形状を変更する関数です。要素の総数は変わりません。


In [1]:
import numpy as np


## 基本的な使い方


In [2]:
# 1次元配列を2次元配列に変換
arr = np.array([1, 2, 3, 4, 5, 6])
print("元の配列:", arr)
print("形状:", arr.shape)

# 2行3列に変換
reshaped = arr.reshape(2, 3)
print("\nreshape(2, 3):")
print(reshaped)
print("新しい形状:", reshaped.shape)


元の配列: [1 2 3 4 5 6]
形状: (6,)

reshape(2, 3):
[[1 2 3]
 [4 5 6]]
新しい形状: (2, 3)


In [3]:
# 2次元配列を1次元配列に変換（フラット化）
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("元の配列:")
print(matrix)
print("形状:", matrix.shape)

# 1次元に変換
flattened = matrix.reshape(6)  # または reshape(-1)
print("\nreshape(6):", flattened)
print("形状:", flattened.shape)


元の配列:
[[1 2 3]
 [4 5 6]]
形状: (2, 3)

reshape(6): [1 2 3 4 5 6]
形状: (6,)


## -1 を使った自動計算


In [4]:
# -1 を使うと、その次元は自動的に計算されます
arr = np.arange(12)  # [0, 1, 2, ..., 11]
print("元の配列:", arr)

# 3行にしたいが、列数は自動計算
reshaped1 = arr.reshape(3, -1)
print("\nreshape(3, -1):")
print(reshaped1)
print("形状:", reshaped1.shape)  # (3, 4)

# 4列にしたいが、行数は自動計算
reshaped2 = arr.reshape(-1, 4)
print("\nreshape(-1, 4):")
print(reshaped2)
print("形状:", reshaped2.shape)  # (3, 4)


元の配列: [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshape(3, -1):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
形状: (3, 4)

reshape(-1, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
形状: (3, 4)


## 多次元配列への変換


In [5]:
# 1次元配列を3次元配列に変換
arr = np.arange(24)  # 24個の要素
print("元の配列:", arr)
print("形状:", arr.shape)

# 2x3x4の3次元配列に変換
reshaped_3d = arr.reshape(2, 3, 4)
print("\nreshape(2, 3, 4):")
print(reshaped_3d)
print("形状:", reshaped_3d.shape)


元の配列: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
形状: (24,)

reshape(2, 3, 4):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
形状: (2, 3, 4)


## 重要な注意点


In [6]:
# reshape() は元の配列のビューを返すことが多い（コピーではない）
arr = np.arange(12)
reshaped = arr.reshape(3, 4)

# 元の配列を変更すると、reshapeした配列も変わる
arr[0] = 999
print("reshapeした配列:")
print(reshaped)  # 最初の要素が999になっている

# コピーが必要な場合は copy() を使う
arr2 = np.arange(12)
reshaped_copy = arr2.reshape(3, 4).copy()
arr2[0] = 888
print("\nコピーした場合:")
print("元の配列[0]:", arr2[0])
print("reshapeした配列[0, 0]:", reshaped_copy[0, 0])  # 変更されていない


reshapeした配列:
[[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]

コピーした場合:
元の配列[0]: 888
reshapeした配列[0, 0]: 0


## よくある使用例


In [7]:
# 例1: 画像データの形状変更（例: 28x28の画像を1次元に）
image = np.random.rand(28, 28)
print("画像の形状:", image.shape)

# 1次元ベクトルに変換（機械学習の入力として使用）
image_flat = image.reshape(-1)  # または reshape(784)
print("フラット化後の形状:", image_flat.shape)

# 元の形状に戻す
image_restored = image_flat.reshape(28, 28)
print("復元後の形状:", image_restored.shape)


画像の形状: (28, 28)
フラット化後の形状: (784,)
復元後の形状: (28, 28)


In [8]:
# 例2: バッチデータの準備
# 100個のサンプル、各サンプルは784次元の特徴ベクトル
batch_size = 10
features = 784
samples = 100

# データを生成
data = np.random.rand(samples, features)
print("元のデータ形状:", data.shape)

# バッチに分割（例: 10個のバッチ、各バッチ10サンプル）
batches = data.reshape(batch_size, samples // batch_size, features)
print("バッチ化後の形状:", batches.shape)  # (10, 10, 784)


元のデータ形状: (100, 784)
バッチ化後の形状: (10, 10, 784)


In [9]:
# 例3: 転置との組み合わせ
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("元の行列:")
print(matrix)
print("形状:", matrix.shape)

# 転置してからreshape
transposed = matrix.T
print("\n転置後:")
print(transposed)
print("形状:", transposed.shape)

# さらに1次元に
flattened = transposed.reshape(-1)
print("\nフラット化後:", flattened)


元の行列:
[[1 2 3]
 [4 5 6]]
形状: (2, 3)

転置後:
[[1 4]
 [2 5]
 [3 6]]
形状: (3, 2)

フラット化後: [1 4 2 5 3 6]
